apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: mynamespace
  labels:
   app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: mynamespace/dotnetdemo:V1 # Replace with the image name from your Docker build process
        ports:
        - containerPort: 80
